version: '3.8'
services:
  pg_database:
    container_name: pg_database
    image: postgres:14.1-alpine
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: dcmemberselection
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data

  go_backend:
    container_name: go_backend
    build:
      context: .
    restart: on-failure
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - pg_database
    links:
      - pg_database
volumes:
  db: